"""empty message

Revision ID: 687bfe2e01b3
Revises: 
Create Date: 2025-06-16 13:49:45.058125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '687bfe2e01b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerte_recommandation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerte_recommandation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dispositif_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alerte', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('recommandation', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['dispositif_id'], ['dispositifs.id'], name=op.f('alerte_recommandation_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
